POST http://localhost:4000/signup
Content-Type: application/json

{
    "name":"sandeep",
    "age":20,
    "email":"chekkasandeep1234@gmail.com",
    "username":"sandeep ch",
    "password":"sandeep123"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"sandeep ch",
    "password":"sandeep123"
}

###
POST http://localhost:4000/logout
Content-Type: application/json

{
    "username":"sandeep ch",
    "password":"sandeep123"
}

###
POST http://localhost:4000/createtask

Content-Type: application/json

{
    "des":"abc",
    "stat":"Not completed..."
}